services:
  web_gameshop:
    build:
      context: ../
      dockerfile: ./dockers/Dockerfile.dev
    command: air
    volumes:
      - ../:/usr/src/web_gameshop
    ports:
      - 8080:8080
    restart:
      always
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project123
      - POSTGRES_DB=project_db

volumes:
  postgres_data: