FROM golang:1.20.1 as base

FROM base as dev

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /usr/src/web_gameshop

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download && go mod verify

COPY ./ .