cors:
  allow_origins: ["*"]
  allow_methods: [GET, POST, PUT]
  allow_credentials: false

db:
  host: db
  user: project
  password: project123
  db_name: project_db
  port: 5432
  sslmode: false

fiber:
  prefork: true
  strict_routing: true
  case_sensitive: true
  port: 8080

migrations:
  mode: auto